import { afterEach, describe, expect, it } from "vitest";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os"; import path from "node:path"; import { execFileSync } from "node:child_process";
import { Store } from "../src/storage/database.js"; import { TaskRepository } from "../src/tasks/repository.js";
import { captureExecutionBinding } from "../src/runtime/correction.js"; import { ExecutionBindingReconciler } from "../src/runtime/executionBindingReconciliation.js";
const dirs: string[]=[]; const stores: Store[]=[]; afterEach(()=>{ stores.splice(0).forEach(s=>s.close()); dirs.splice(0).forEach(d=>rmSync(d,{recursive:true,force:true})); });
function git(dir:string,...args:string[]):string { return execFileSync("git",args,{cwd:dir,encoding:"utf8",windowsHide:true}).trim(); }
function setup() { const root=mkdtempSync(path.join(os.tmpdir(),"binding-reconcile-")); dirs.push(root); const dir=path.join(root,"repo"); git(root,"init",dir); git(dir,"config","user.email","test@example.invalid"); git(dir,"config","user.name","Test"); git(dir,"checkout","-b","approved"); writeFileSync(path.join(dir,"p.txt"),"one\n"); git(dir,"add","p.txt"); git(dir,"commit","-m","base"); const oldSha=git(dir,"rev-parse","HEAD");
  const store=new Store(path.join(root,"runtime.db")); stores.push(store); store.db.prepare("INSERT INTO projects(project_id,name,workspace,ssot_paths_json,status,updated_at) VALUES(?,?,?,?,?,?)").run("p","P",dir,"[]","ACTIVE",store.now()); const tasks=new TaskRepository(store); tasks.create({taskId:"t",projectId:"p",title:"T",goal:"G",role:"DEVELOPER",requiredCapabilities:[],status:"WAITING_MAIN",workspace:dir,readContext:{},fileScope:[],doNot:[],validation:[],owner:"OWNER"}); store.upsertRuntimeState("task:execution_binding:t",captureExecutionBinding(tasks.get("t")!));
  writeFileSync(path.join(dir,"p.txt"),"two\n"); git(dir,"add","p.txt"); git(dir,"commit","-m","approved descendant"); const newSha=git(dir,"rev-parse","HEAD"); return {dir,store,tasks,oldSha,newSha,r:new ExecutionBindingReconciler(store,tasks)}; }
describe("ExecutionBindingReconciler",()=>{
  it("accepts only the exact clean descendant and preserves old evidence",()=>{const x=setup(); const out=x.r.reconcile("t","r1",x.oldSha,x.newSha,"owner approved"); expect(out.status).toBe("SUCCEEDED"); const audit=x.store.db.prepare("SELECT old_binding_json,new_binding_json FROM execution_binding_reconciliations WHERE reconciliation_id='r1'").get() as {old_binding_json:string;new_binding_json:string}; expect(JSON.parse(audit.old_binding_json).base_sha).toBe(x.oldSha); expect(JSON.parse(audit.new_binding_json).base_sha).toBe(x.newSha); expect(x.store.getRuntimeState<{base_sha:string}>("task:execution_binding:t")?.base_sha).toBe(x.newSha); expect(()=>x.r.reconcile("t","r2",x.oldSha,x.newSha,"duplicate")).toThrow("DUPLICATE");});
  it("rejects wrong old SHA, non-descendant, dirty worktree, terminal, active Worker, hold, and wrong workspace",()=>{let x=setup(); expect(()=>x.r.reconcile("t","a","0".repeat(40),x.newSha,"r")).toThrow("EXPECTED_OLD_MISMATCH");
    x=setup(); git(x.dir,"checkout","--orphan","other"); writeFileSync(path.join(x.dir,"q.txt"),"q\n"); git(x.dir,"add","q.txt"); git(x.dir,"commit","-m","other"); const other=git(x.dir,"rev-parse","HEAD"); git(x.dir,"branch","-M","approved"); expect(()=>x.r.reconcile("t","b",x.oldSha,other,"r")).toThrow("NOT_DESCENDANT");
    x=setup(); writeFileSync(path.join(x.dir,"dirty.txt"),"dirty"); expect(()=>x.r.reconcile("t","c",x.oldSha,x.newSha,"r")).toThrow("DIRTY_WORKTREE");
    x=setup(); x.store.db.prepare("UPDATE tasks SET status='PASS' WHERE task_id='t'").run(); expect(()=>x.r.reconcile("t","d",x.oldSha,x.newSha,"r")).toThrow("TERMINAL_TASK");
    x=setup(); x.store.db.prepare("INSERT INTO worker_processes(process_id,agent_id,task_id,attempt,pid,working_dir,started_at,last_seen,status,log_path) VALUES(?,?,?,?,?,?,?,?,?,?)").run("w","CODEX","t",1,1,x.dir,x.store.now(),x.store.now(),"RUNNING","l"); expect(()=>x.r.reconcile("t","e",x.oldSha,x.newSha,"r")).toThrow("ACTIVE_WORKER");
    x=setup(); x.store.db.prepare("UPDATE tasks SET execution_hold=1 WHERE task_id='t'").run(); expect(()=>x.r.reconcile("t","f",x.oldSha,x.newSha,"r")).toThrow("EXECUTION_HOLD");
    x=setup(); const binding=x.store.getRuntimeState<Record<string,string>>("task:execution_binding:t")!; binding.worktree=x.dir+"-wrong"; x.store.upsertRuntimeState("task:execution_binding:t",binding); expect(()=>x.r.reconcile("t","g",x.oldSha,x.newSha,"r")).toThrow("WORKSPACE_MISMATCH"); },15_000);
});
